substitutions:
  name: powermust
  device_description: "Monitor and control a Mustek Powermust 800 via RS232"
  external_components_source: github://syssi/esphome-powermust@main
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-powermust"
    version: 1.1.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 2400
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\r"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

powermust:
  - id: powermust0
    uart_id: uart_0

binary_sensor:
  - platform: powermust
    powermust_id: powermust0
    utility_fail:
      name: "${name} utility fail"
    battery_low:
      name: "${name} battery low"
    bypass_active:
      name: "${name} bypass active"
    ups_failed:
      name: "${name} ups failed"
    ups_type_standby:
      name: "${name} ups type standby"
    test_in_progress:
      name: "${name} test in progress"
    shutdown_active:
      name: "${name} shutdown active"
    beeper_on:
      name: "${name} beeper on"

sensor:
  - platform: powermust
    powermust_id: powermust0
    grid_voltage:
      name: "${name} grid voltage"
    grid_fault_voltage:
      name: "${name} grid fault voltage"
    ac_output_voltage:
      name: "${name} ac output voltage"
    ac_output_load_percent:
      name: "${name} ac output load percent"
    grid_frequency:
      name: "${name} grid frequency"
    battery_voltage:
      name: "${name} battery voltage"
    temperature:
      name: "${name} temperature"
    # ac_output_rating_voltage:
    #   name: "${name} ac output rating voltage"
    # ac_output_rating_current:
    #   name: "${name} ac output rating current"
    # battery_rating_voltage:
    #   name: "${name} battery rating voltage"
    # ac_output_rating_frequency:
    #   name: "${name} ac output rating frequency"

switch:
  - platform: powermust
    powermust_id: powermust0
    beeper:
      name: "${name} beeper"
    quick_test:
      name: "${name} quick test"
    # Unsupported by Powermust 800 USB
    # deep_test:
    #   name: "${name} deep test"
    # ten_minutes_test:
    #   name: "${name} 10min test"

text_sensor:
  - platform: powermust
    powermust_id: powermust0
    last_q1:
      name: "${name} last q1"
    last_f:
      name: "${name} last f"
